# Create App using:
#  cs app create shared/boutique app.yaml
workspaces:
- name: app
  checkouts:
  - path: src/demo
    repo:
      git: https://github.com/GoogleCloudPlatform/microservices-demo
    version_spec: v0.3.9
  - path: src/solutions
    repo:
      git: https://github.com/crafting-demo/solutions
  packages:
  - name: golang
    version: ~1.18
  - name: nodejs
    version: ~16
  - name: openjdk
    version: ~14
  base_snapshot: shared/base-boutique-r1
  env:
  - GOOGLE_APPLICATION_CREDENTIALS=/run/sandbox/fs/secrets/shared/shared/gcp-account.json
  - KUBECONFIG=/run/sandbox/fs/secrets/shared/shared/kubeconfig-demo1.yaml
