---
overview: |
  # AWS Resources in Sandbox
  
  This sandbox is created with an EC2 Windows VM.
  Click the endpoint [rdp]({{endpoints.rdp.url}}) to access the Windows desktop
  or click the resource `windows` to see the detailed instructions.

endpoints:
- name: rdp
  http:
    path: /guacamole/
    routes:
    - path_prefix: /
      backend:
        target: dev
        port: guacamole
workspaces:
- name: dev
  ports:
  - name: guacamole
    port: 8080
    protocol: HTTP/TCP
  probes:
    readiness:
    - name: guacamole
      http_get:
        port: 8080
        path: /guacamole/
  checkouts:
  - path: demo
    repo:
      git: https://github.com/crafting-demo/solutions
    manifest:
      overlays:
      - file: apps/aws-windowsvm/manifest.yaml
  env:
  - AWS_CONFIG_FILE=/run/sandbox/fs/secrets/shared/aws-config
  base_snapshot: shared/base-dev-r1
  home_snapshot: shared/home-dev-r1
dependencies:
- name: guacamoledb
  service_type: mysql
  properties:
    database: guacamole
    username: guacamole
    password: guacamole
  snapshot: shared/guacamoledb-r1
resources:
- name: windows
  brief: EC2 Windows VM
  details: |
    EC2 Windows VM:
    
    - Hostname: {{state.public_dns.value}}
    - PublicIP: {{state.public_ip.value}}

    Access via [RDP]({{endpoints.rdp.url}}), or use the following config `{{sandbox.name}}.rdp`:

    ```
    auto connect:i:1
    full address:s:{{state.public_dns.value}}
    username:s:Administrator
    ```

    Password can be found in `/run/sandbox/fs/resources/windows/state`.
  terraform:
    workspace: dev
    dir: demo/apps/aws-windowsvm/tf
    run:
      timeout: 1800s
    save_state: true
customizations:
- property_set:
    type: crafting.dev/sandbox/express-workspace
    properties:
      os: windows
      summary: 'Windows on an EC2 instance'
      ip: '{{resoures.windows.state.public_ip.value}}'
      host: '{{resources.windows.state.public_dns.value}}'
      webrdp_url: '{{endpoints.rdp.url}}'
