---
overview: |
  # AWS Resources in Sandbox
  
  This App demonstrates how to manage the lifecycle
  of AWS resources per sandbox.

endpoints:
- name: rdp
  http:
    path: /guacamole/
    routes:
    - path_prefix: /
      backend:
        target: dev
        port: guacamole
workspaces:
- name: dev
  ports:
  - name: guacamole
    port: 8080
    protocol: HTTP/TCP
  checkouts:
  - path: demo
    repo:
      git: git@github.com:crafting-demo/self-hosting
    manifest:
      overlays:
      - file: apps/aws-windowsvm/manifest.yaml
  env:
  - AWS_CONFIG_FILE=/run/sandbox/fs/secrets/shared/aws-config
  base_snapshot: base/dev/1
  home_snapshot: home/dev/1
containers:
- name: guacd
  image: guacamole/guacd:1.4.0
  ports:
  - name: guacd
    port: 4822
    protocol: TCP
dependencies:
- name: guacamoledb
  service_type: mysql
  properties:
    database: guacamole
    username: guacamole
    password: guacamole
  snapshot: mysql/guacamole/base/1
resources:
- name: windows
  brief: EC2 Windows VM
  details: |
    EC2 Windows VM:
    
    - Hostname: {{data.public_dns.value}}
    - PublicIP: {{data.public_ip.value}}

    Access via [RDP]({{endpoints.rdp.url}}).
    _Administrator_ password can be found in `/run/sandbox/fs/resources/windows/output`.

  handlers:
    on_create:
      max_retries: 3
      timeout: 1800s
      use_workspace:
        name: dev
        run:
          dir: demo/apps/aws-windowsvm/tf
          cmd: |
            set -ex
            terraform init >&2
            terraform apply -auto-approve >&2
            terraform output -json
    on_delete:
      max_retries: 3
      timeout: 1800s
      use_workspace:
        name: dev
        run:
          dir: demo/apps/aws-windowsvm/tf
          cmd: terraform destroy -auto-approve >&2
